# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1475, 894)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Patch_label = QtWidgets.QLabel(self.centralwidget)
        self.Patch_label.setGeometry(QtCore.QRect(10, 0, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Patch_label.setFont(font)
        self.Patch_label.setObjectName("Patch_label")
        self.euwCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.euwCheckBox.setGeometry(QtCore.QRect(290, 10, 51, 21))
        self.euwCheckBox.setChecked(True)
        self.euwCheckBox.setObjectName("euwCheckBox")
        self.krCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.krCheckBox.setGeometry(QtCore.QRect(290, 30, 51, 21))
        self.krCheckBox.setChecked(False)
        self.krCheckBox.setObjectName("krCheckBox")
        self.traitsButton = QtWidgets.QPushButton(self.centralwidget)
        self.traitsButton.setGeometry(QtCore.QRect(1340, 690, 111, 31))
        self.traitsButton.setObjectName("traitsButton")
        self.championsButton = QtWidgets.QPushButton(self.centralwidget)
        self.championsButton.setGeometry(QtCore.QRect(1340, 730, 111, 31))
        self.championsButton.setObjectName("championsButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 1451, 571))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Bengali")
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.loadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadDataButton.setGeometry(QtCore.QRect(710, 10, 80, 41))
        self.loadDataButton.setObjectName("loadDataButton")
        self.traitFilter1 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter1.setGeometry(QtCore.QRect(40, 690, 131, 31))
        self.traitFilter1.setObjectName("traitFilter1")
        self.traitFilter3 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter3.setGeometry(QtCore.QRect(40, 770, 131, 31))
        self.traitFilter3.setObjectName("traitFilter3")
        self.traitFilter2 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter2.setGeometry(QtCore.QRect(40, 730, 131, 31))
        self.traitFilter2.setObjectName("traitFilter2")
        self.traitFilter4 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter4.setGeometry(QtCore.QRect(40, 810, 131, 31))
        self.traitFilter4.setObjectName("traitFilter4")
        self.traitFilterSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider1.setGeometry(QtCore.QRect(210, 695, 121, 21))
        self.traitFilterSlider1.setMinimum(1)
        self.traitFilterSlider1.setMaximum(4)
        self.traitFilterSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider1.setTickInterval(1)
        self.traitFilterSlider1.setObjectName("traitFilterSlider1")
        self.traitFilterSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider2.setGeometry(QtCore.QRect(210, 740, 121, 21))
        self.traitFilterSlider2.setMinimum(1)
        self.traitFilterSlider2.setMaximum(4)
        self.traitFilterSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider2.setTickInterval(1)
        self.traitFilterSlider2.setObjectName("traitFilterSlider2")
        self.traitFilterSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider3.setGeometry(QtCore.QRect(210, 780, 121, 21))
        self.traitFilterSlider3.setMinimum(1)
        self.traitFilterSlider3.setMaximum(4)
        self.traitFilterSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider3.setTickInterval(1)
        self.traitFilterSlider3.setObjectName("traitFilterSlider3")
        self.traitFilterSlider4 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider4.setGeometry(QtCore.QRect(210, 820, 121, 21))
        self.traitFilterSlider4.setMinimum(1)
        self.traitFilterSlider4.setMaximum(4)
        self.traitFilterSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider4.setTickInterval(1)
        self.traitFilterSlider4.setObjectName("traitFilterSlider4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1360, 660, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 650, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 650, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.championFilterSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider3.setGeometry(QtCore.QRect(570, 780, 111, 21))
        self.championFilterSlider3.setMinimum(1)
        self.championFilterSlider3.setMaximum(3)
        self.championFilterSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider3.setTickInterval(1)
        self.championFilterSlider3.setObjectName("championFilterSlider3")
        self.championFilterSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider2.setGeometry(QtCore.QRect(570, 740, 111, 21))
        self.championFilterSlider2.setMinimum(1)
        self.championFilterSlider2.setMaximum(3)
        self.championFilterSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider2.setTickInterval(1)
        self.championFilterSlider2.setObjectName("championFilterSlider2")
        self.championFilterSlider4 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider4.setGeometry(QtCore.QRect(570, 820, 111, 21))
        self.championFilterSlider4.setMinimum(1)
        self.championFilterSlider4.setMaximum(3)
        self.championFilterSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider4.setTickInterval(1)
        self.championFilterSlider4.setObjectName("championFilterSlider4")
        self.championFilterSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider1.setGeometry(QtCore.QRect(570, 700, 111, 21))
        self.championFilterSlider1.setMinimum(1)
        self.championFilterSlider1.setMaximum(3)
        self.championFilterSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider1.setTickInterval(1)
        self.championFilterSlider1.setObjectName("championFilterSlider1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 650, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 660, 54, 17))
        self.label_5.setObjectName("label_5")
        self.traitFilterCheckBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox1.setGeometry(QtCore.QRect(10, 690, 21, 23))
        self.traitFilterCheckBox1.setText("")
        self.traitFilterCheckBox1.setObjectName("traitFilterCheckBox1")
        self.traitFilterCheckBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox2.setGeometry(QtCore.QRect(10, 730, 21, 23))
        self.traitFilterCheckBox2.setText("")
        self.traitFilterCheckBox2.setObjectName("traitFilterCheckBox2")
        self.traitFilterCheckBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox4.setGeometry(QtCore.QRect(10, 810, 21, 23))
        self.traitFilterCheckBox4.setText("")
        self.traitFilterCheckBox4.setObjectName("traitFilterCheckBox4")
        self.traitFilterCheckBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox3.setGeometry(QtCore.QRect(10, 770, 21, 23))
        self.traitFilterCheckBox3.setText("")
        self.traitFilterCheckBox3.setObjectName("traitFilterCheckBox3")
        self.championFilterCheckBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox4.setGeometry(QtCore.QRect(360, 810, 21, 23))
        self.championFilterCheckBox4.setText("")
        self.championFilterCheckBox4.setObjectName("championFilterCheckBox4")
        self.championFilterCheckBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox3.setGeometry(QtCore.QRect(360, 770, 21, 23))
        self.championFilterCheckBox3.setText("")
        self.championFilterCheckBox3.setObjectName("championFilterCheckBox3")
        self.championFilterCheckBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox1.setGeometry(QtCore.QRect(360, 690, 21, 23))
        self.championFilterCheckBox1.setText("")
        self.championFilterCheckBox1.setObjectName("championFilterCheckBox1")
        self.championFilterCheckBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox2.setGeometry(QtCore.QRect(360, 730, 21, 23))
        self.championFilterCheckBox2.setText("")
        self.championFilterCheckBox2.setObjectName("championFilterCheckBox2")
        self.currentPatchFilter = QtWidgets.QLineEdit(self.centralwidget)
        self.currentPatchFilter.setGeometry(QtCore.QRect(230, 10, 41, 31))
        self.currentPatchFilter.setObjectName("currentPatchFilter")
        self.playersPerRegion = QtWidgets.QLineEdit(self.centralwidget)
        self.playersPerRegion.setGeometry(QtCore.QRect(460, 20, 111, 31))
        self.playersPerRegion.setObjectName("playersPerRegion")
        self.gamesPerPlayer = QtWidgets.QLineEdit(self.centralwidget)
        self.gamesPerPlayer.setGeometry(QtCore.QRect(590, 20, 111, 31))
        self.gamesPerPlayer.setObjectName("gamesPerPlayer")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(590, 0, 101, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 0, 111, 20))
        self.label_7.setObjectName("label_7")
        self.challengerRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.challengerRadioButton.setGeometry(QtCore.QRect(350, 0, 81, 23))
        self.challengerRadioButton.setChecked(True)
        self.challengerRadioButton.setObjectName("challengerRadioButton")
        self.grandmasterRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.grandmasterRadioButton.setGeometry(QtCore.QRect(350, 20, 101, 23))
        self.grandmasterRadioButton.setObjectName("grandmasterRadioButton")
        self.masterRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.masterRadioButton.setGeometry(QtCore.QRect(350, 40, 82, 23))
        self.masterRadioButton.setObjectName("masterRadioButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(720, 660, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(890, 660, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.placementFilter = QtWidgets.QSlider(self.centralwidget)
        self.placementFilter.setGeometry(QtCore.QRect(890, 720, 160, 21))
        self.placementFilter.setMinimum(1)
        self.placementFilter.setMaximum(8)
        self.placementFilter.setProperty("value", 4)
        self.placementFilter.setSliderPosition(4)
        self.placementFilter.setOrientation(QtCore.Qt.Horizontal)
        self.placementFilter.setInvertedAppearance(False)
        self.placementFilter.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.placementFilter.setTickInterval(1)
        self.placementFilter.setObjectName("placementFilter")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1030, 700, 54, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(880, 700, 54, 17))
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(220, 670, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(250, 670, 16, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(280, 670, 16, 17))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(310, 670, 16, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(570, 680, 16, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(670, 680, 16, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(620, 680, 16, 17))
        self.label_20.setObjectName("label_20")
        self.itemFilter1 = QtWidgets.QComboBox(self.centralwidget)
        self.itemFilter1.setGeometry(QtCore.QRect(720, 690, 131, 31))
        self.itemFilter1.setObjectName("itemFilter1")
        self.championFilter1 = QtWidgets.QComboBox(self.centralwidget)
        self.championFilter1.setGeometry(QtCore.QRect(400, 690, 131, 31))
        self.championFilter1.setObjectName("championFilter1")
        self.championFilter3 = QtWidgets.QComboBox(self.centralwidget)
        self.championFilter3.setGeometry(QtCore.QRect(400, 770, 131, 31))
        self.championFilter3.setObjectName("championFilter3")
        self.championFilter2 = QtWidgets.QComboBox(self.centralwidget)
        self.championFilter2.setGeometry(QtCore.QRect(400, 730, 131, 31))
        self.championFilter2.setObjectName("championFilter2")
        self.championFilter4 = QtWidgets.QComboBox(self.centralwidget)
        self.championFilter4.setGeometry(QtCore.QRect(400, 810, 131, 31))
        self.championFilter4.setObjectName("championFilter4")
        self.itemFilterCheckBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.itemFilterCheckBox1.setGeometry(QtCore.QRect(700, 690, 21, 23))
        self.itemFilterCheckBox1.setText("")
        self.itemFilterCheckBox1.setObjectName("itemFilterCheckBox1")
        self.traitFilterTierCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterTierCheckBox.setGeometry(QtCore.QRect(180, 750, 21, 23))
        self.traitFilterTierCheckBox.setText("")
        self.traitFilterTierCheckBox.setObjectName("traitFilterTierCheckBox")
        self.championStarFilterCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.championStarFilterCheckBox.setGeometry(QtCore.QRect(540, 750, 21, 23))
        self.championStarFilterCheckBox.setText("")
        self.championStarFilterCheckBox.setObjectName("championStarFilterCheckBox")
        self.itemFilter2 = QtWidgets.QComboBox(self.centralwidget)
        self.itemFilter2.setGeometry(QtCore.QRect(720, 730, 131, 31))
        self.itemFilter2.setObjectName("itemFilter2")
        self.itemFilterCheckBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.itemFilterCheckBox2.setGeometry(QtCore.QRect(700, 730, 21, 23))
        self.itemFilterCheckBox2.setText("")
        self.itemFilterCheckBox2.setObjectName("itemFilterCheckBox2")
        self.itemFilter3 = QtWidgets.QComboBox(self.centralwidget)
        self.itemFilter3.setGeometry(QtCore.QRect(720, 770, 131, 31))
        self.itemFilter3.setObjectName("itemFilter3")
        self.itemFilterCheckBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.itemFilterCheckBox3.setGeometry(QtCore.QRect(700, 770, 21, 23))
        self.itemFilterCheckBox3.setText("")
        self.itemFilterCheckBox3.setObjectName("itemFilterCheckBox3")
        self.itemFilter4 = QtWidgets.QComboBox(self.centralwidget)
        self.itemFilter4.setGeometry(QtCore.QRect(720, 810, 131, 31))
        self.itemFilter4.setObjectName("itemFilter4")
        self.itemFilterCheckBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.itemFilterCheckBox4.setGeometry(QtCore.QRect(700, 810, 21, 23))
        self.itemFilterCheckBox4.setText("")
        self.itemFilterCheckBox4.setObjectName("itemFilterCheckBox4")
        self.resetDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetDataButton.setGeometry(QtCore.QRect(1380, 10, 80, 41))
        self.resetDataButton.setObjectName("resetDataButton")
        self.bestInSlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.bestInSlotButton.setGeometry(QtCore.QRect(1140, 710, 111, 21))
        self.bestInSlotButton.setObjectName("bestInSlotButton")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1140, 670, 16, 17))
        self.label_21.setObjectName("label_21")
        self.bestInSlotSlider = QtWidgets.QSlider(self.centralwidget)
        self.bestInSlotSlider.setGeometry(QtCore.QRect(1139, 690, 111, 21))
        self.bestInSlotSlider.setMinimum(1)
        self.bestInSlotSlider.setMaximum(3)
        self.bestInSlotSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bestInSlotSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.bestInSlotSlider.setTickInterval(1)
        self.bestInSlotSlider.setObjectName("bestInSlotSlider")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1240, 670, 16, 17))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(1190, 670, 16, 17))
        self.label_24.setObjectName("label_24")
        self.nTraitFilterSlider = QtWidgets.QSlider(self.centralwidget)
        self.nTraitFilterSlider.setGeometry(QtCore.QRect(1140, 760, 111, 21))
        self.nTraitFilterSlider.setMinimum(1)
        self.nTraitFilterSlider.setMaximum(3)
        self.nTraitFilterSlider.setOrientation(QtCore.Qt.Horizontal)
        self.nTraitFilterSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.nTraitFilterSlider.setTickInterval(1)
        self.nTraitFilterSlider.setObjectName("nTraitFilterSlider")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(1240, 740, 16, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(1190, 740, 16, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(1140, 740, 16, 17))
        self.label_28.setObjectName("label_28")
        self.groupNTraitsButton = QtWidgets.QPushButton(self.centralwidget)
        self.groupNTraitsButton.setGeometry(QtCore.QRect(1140, 780, 111, 21))
        self.groupNTraitsButton.setObjectName("groupNTraitsButton")
        self.one_unit_trait_ignore_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.one_unit_trait_ignore_checkbox.setGeometry(QtCore.QRect(880, 760, 171, 23))
        self.one_unit_trait_ignore_checkbox.setObjectName("one_unit_trait_ignore_checkbox")
        self.analyzedMatchesCounter = QtWidgets.QLineEdit(self.centralwidget)
        self.analyzedMatchesCounter.setGeometry(QtCore.QRect(1310, 40, 61, 21))
        self.analyzedMatchesCounter.setReadOnly(True)
        self.analyzedMatchesCounter.setObjectName("analyzedMatchesCounter")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(1310, 0, 51, 20))
        self.label_23.setObjectName("label_23")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(1310, 20, 51, 20))
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(880, 800, 31, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(880, 820, 111, 20))
        self.label_32.setObjectName("label_32")
        self.minOccurencesFilter = QtWidgets.QLineEdit(self.centralwidget)
        self.minOccurencesFilter.setGeometry(QtCore.QRect(920, 800, 51, 21))
        self.minOccurencesFilter.setObjectName("minOccurencesFilter")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1475, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "TFT Challenger Meta Evaluator"))
        self.Patch_label.setText(_translate("mainWindow", "Current Patch:"))
        self.euwCheckBox.setText(_translate("mainWindow", "EUW"))
        self.krCheckBox.setText(_translate("mainWindow", "KR"))
        self.traitsButton.setText(_translate("mainWindow", "Traits"))
        self.championsButton.setText(_translate("mainWindow", "Champions"))
        self.tableWidget.setSortingEnabled(False)
        self.loadDataButton.setText(_translate("mainWindow", "Load Data"))
        self.label.setText(_translate("mainWindow", "Search"))
        self.label_2.setText(_translate("mainWindow", "Trait Filter"))
        self.label_3.setText(_translate("mainWindow", "Champion Filter"))
        self.label_4.setText(_translate("mainWindow", "Tier"))
        self.label_5.setText(_translate("mainWindow", "Star"))
        self.currentPatchFilter.setText(_translate("mainWindow", "11.7"))
        self.playersPerRegion.setText(_translate("mainWindow", "8"))
        self.gamesPerPlayer.setText(_translate("mainWindow", "8"))
        self.label_6.setText(_translate("mainWindow", "Games per Player"))
        self.label_7.setText(_translate("mainWindow", "Players per Region"))
        self.challengerRadioButton.setText(_translate("mainWindow", "Challenger"))
        self.grandmasterRadioButton.setText(_translate("mainWindow", "Grandmaster"))
        self.masterRadioButton.setText(_translate("mainWindow", "Master"))
        self.label_8.setText(_translate("mainWindow", "Item Filter"))
        self.label_9.setText(_translate("mainWindow", "Placement Filter"))
        self.label_10.setText(_translate("mainWindow", "Top 8"))
        self.label_11.setText(_translate("mainWindow", "Top 1"))
        self.label_14.setText(_translate("mainWindow", "1"))
        self.label_15.setText(_translate("mainWindow", "2"))
        self.label_16.setText(_translate("mainWindow", "3"))
        self.label_17.setText(_translate("mainWindow", "4"))
        self.label_18.setText(_translate("mainWindow", "1"))
        self.label_19.setText(_translate("mainWindow", "3"))
        self.label_20.setText(_translate("mainWindow", "2"))
        self.resetDataButton.setText(_translate("mainWindow", "Reset Data"))
        self.bestInSlotButton.setText(_translate("mainWindow", "Best in Slot Items"))
        self.label_21.setText(_translate("mainWindow", "1"))
        self.label_22.setText(_translate("mainWindow", "3"))
        self.label_24.setText(_translate("mainWindow", "2"))
        self.label_26.setText(_translate("mainWindow", "3"))
        self.label_27.setText(_translate("mainWindow", "2"))
        self.label_28.setText(_translate("mainWindow", "1"))
        self.groupNTraitsButton.setText(_translate("mainWindow", "Group n Traits"))
        self.one_unit_trait_ignore_checkbox.setText(_translate("mainWindow", "Ignore 1-unit traits"))
        self.analyzedMatchesCounter.setText(_translate("mainWindow", "0"))
        self.label_23.setText(_translate("mainWindow", "Analyzed"))
        self.label_29.setText(_translate("mainWindow", "matches"))
        self.label_31.setText(_translate("mainWindow", "Show "))
        self.label_32.setText(_translate("mainWindow", "or more occurences"))
        self.minOccurencesFilter.setText(_translate("mainWindow", "2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
