# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1475, 894)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Patch_label = QtWidgets.QLabel(self.centralwidget)
        self.Patch_label.setGeometry(QtCore.QRect(10, 0, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Patch_label.setFont(font)
        self.Patch_label.setObjectName("Patch_label")
        self.euwCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.euwCheckBox.setGeometry(QtCore.QRect(290, 10, 51, 21))
        self.euwCheckBox.setChecked(True)
        self.euwCheckBox.setObjectName("euwCheckBox")
        self.krCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.krCheckBox.setGeometry(QtCore.QRect(290, 30, 51, 21))
        self.krCheckBox.setChecked(False)
        self.krCheckBox.setObjectName("krCheckBox")
        self.traitsButton = QtWidgets.QPushButton(self.centralwidget)
        self.traitsButton.setGeometry(QtCore.QRect(810, 690, 111, 41))
        self.traitsButton.setObjectName("traitsButton")
        self.championsButton = QtWidgets.QPushButton(self.centralwidget)
        self.championsButton.setGeometry(QtCore.QRect(810, 740, 111, 41))
        self.championsButton.setObjectName("championsButton")
        self.itemsButton = QtWidgets.QPushButton(self.centralwidget)
        self.itemsButton.setGeometry(QtCore.QRect(810, 790, 111, 41))
        self.itemsButton.setObjectName("itemsButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 1451, 581))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Bengali")
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.loadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadDataButton.setGeometry(QtCore.QRect(710, 10, 80, 41))
        self.loadDataButton.setObjectName("loadDataButton")
        self.traitFilter1 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter1.setGeometry(QtCore.QRect(40, 690, 131, 31))
        self.traitFilter1.setObjectName("traitFilter1")
        self.traitFilter3 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter3.setGeometry(QtCore.QRect(40, 770, 131, 31))
        self.traitFilter3.setObjectName("traitFilter3")
        self.traitFilter2 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter2.setGeometry(QtCore.QRect(40, 730, 131, 31))
        self.traitFilter2.setObjectName("traitFilter2")
        self.traitFilter4 = QtWidgets.QComboBox(self.centralwidget)
        self.traitFilter4.setGeometry(QtCore.QRect(40, 810, 131, 31))
        self.traitFilter4.setObjectName("traitFilter4")
        self.traitFilterSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider1.setGeometry(QtCore.QRect(180, 695, 160, 21))
        self.traitFilterSlider1.setMinimum(1)
        self.traitFilterSlider1.setMaximum(4)
        self.traitFilterSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider1.setTickInterval(1)
        self.traitFilterSlider1.setObjectName("traitFilterSlider1")
        self.traitFilterSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider2.setGeometry(QtCore.QRect(180, 740, 160, 21))
        self.traitFilterSlider2.setMinimum(1)
        self.traitFilterSlider2.setMaximum(4)
        self.traitFilterSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider2.setTickInterval(1)
        self.traitFilterSlider2.setObjectName("traitFilterSlider2")
        self.traitFilterSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider3.setGeometry(QtCore.QRect(180, 780, 160, 21))
        self.traitFilterSlider3.setMinimum(1)
        self.traitFilterSlider3.setMaximum(4)
        self.traitFilterSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider3.setTickInterval(1)
        self.traitFilterSlider3.setObjectName("traitFilterSlider3")
        self.traitFilterSlider4 = QtWidgets.QSlider(self.centralwidget)
        self.traitFilterSlider4.setGeometry(QtCore.QRect(180, 820, 160, 21))
        self.traitFilterSlider4.setMinimum(1)
        self.traitFilterSlider4.setMaximum(4)
        self.traitFilterSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.traitFilterSlider4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.traitFilterSlider4.setTickInterval(1)
        self.traitFilterSlider4.setObjectName("traitFilterSlider4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(830, 650, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 650, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 650, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Batak")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.championFilterSlider3 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider3.setGeometry(QtCore.QRect(610, 780, 160, 21))
        self.championFilterSlider3.setMinimum(1)
        self.championFilterSlider3.setMaximum(3)
        self.championFilterSlider3.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider3.setTickInterval(1)
        self.championFilterSlider3.setObjectName("championFilterSlider3")
        self.championFilterSlider2 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider2.setGeometry(QtCore.QRect(610, 740, 160, 21))
        self.championFilterSlider2.setMinimum(1)
        self.championFilterSlider2.setMaximum(3)
        self.championFilterSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider2.setTickInterval(1)
        self.championFilterSlider2.setObjectName("championFilterSlider2")
        self.championFilterSlider4 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider4.setGeometry(QtCore.QRect(610, 820, 160, 21))
        self.championFilterSlider4.setMinimum(1)
        self.championFilterSlider4.setMaximum(3)
        self.championFilterSlider4.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider4.setTickInterval(1)
        self.championFilterSlider4.setObjectName("championFilterSlider4")
        self.championFilterSlider1 = QtWidgets.QSlider(self.centralwidget)
        self.championFilterSlider1.setGeometry(QtCore.QRect(610, 700, 160, 21))
        self.championFilterSlider1.setMinimum(1)
        self.championFilterSlider1.setMaximum(3)
        self.championFilterSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.championFilterSlider1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.championFilterSlider1.setTickInterval(1)
        self.championFilterSlider1.setObjectName("championFilterSlider1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 670, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 670, 54, 17))
        self.label_5.setObjectName("label_5")
        self.traitFilterCheckBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox1.setGeometry(QtCore.QRect(10, 690, 21, 23))
        self.traitFilterCheckBox1.setText("")
        self.traitFilterCheckBox1.setObjectName("traitFilterCheckBox1")
        self.traitFilterCheckBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox2.setGeometry(QtCore.QRect(10, 730, 21, 23))
        self.traitFilterCheckBox2.setText("")
        self.traitFilterCheckBox2.setObjectName("traitFilterCheckBox2")
        self.traitFilterCheckBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox4.setGeometry(QtCore.QRect(10, 810, 21, 23))
        self.traitFilterCheckBox4.setText("")
        self.traitFilterCheckBox4.setObjectName("traitFilterCheckBox4")
        self.traitFilterCheckBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.traitFilterCheckBox3.setGeometry(QtCore.QRect(10, 770, 21, 23))
        self.traitFilterCheckBox3.setText("")
        self.traitFilterCheckBox3.setObjectName("traitFilterCheckBox3")
        self.championFilterCheckBox4 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox4.setGeometry(QtCore.QRect(380, 810, 21, 23))
        self.championFilterCheckBox4.setText("")
        self.championFilterCheckBox4.setObjectName("championFilterCheckBox4")
        self.championFilterCheckBox3 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox3.setGeometry(QtCore.QRect(380, 770, 21, 23))
        self.championFilterCheckBox3.setText("")
        self.championFilterCheckBox3.setObjectName("championFilterCheckBox3")
        self.championFilterCheckBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox1.setGeometry(QtCore.QRect(380, 690, 21, 23))
        self.championFilterCheckBox1.setText("")
        self.championFilterCheckBox1.setObjectName("championFilterCheckBox1")
        self.championFilterCheckBox2 = QtWidgets.QCheckBox(self.centralwidget)
        self.championFilterCheckBox2.setGeometry(QtCore.QRect(380, 730, 21, 23))
        self.championFilterCheckBox2.setText("")
        self.championFilterCheckBox2.setObjectName("championFilterCheckBox2")
        self.championFilter1 = QtWidgets.QLineEdit(self.centralwidget)
        self.championFilter1.setGeometry(QtCore.QRect(410, 690, 191, 25))
        self.championFilter1.setObjectName("championFilter1")
        self.championFilter2 = QtWidgets.QLineEdit(self.centralwidget)
        self.championFilter2.setGeometry(QtCore.QRect(410, 730, 191, 25))
        self.championFilter2.setObjectName("championFilter2")
        self.championFilter3 = QtWidgets.QLineEdit(self.centralwidget)
        self.championFilter3.setGeometry(QtCore.QRect(410, 770, 191, 25))
        self.championFilter3.setObjectName("championFilter3")
        self.championFilter4 = QtWidgets.QLineEdit(self.centralwidget)
        self.championFilter4.setGeometry(QtCore.QRect(410, 810, 191, 25))
        self.championFilter4.setObjectName("championFilter4")
        self.currentPatchFilter = QtWidgets.QLineEdit(self.centralwidget)
        self.currentPatchFilter.setGeometry(QtCore.QRect(230, 10, 41, 31))
        self.currentPatchFilter.setObjectName("currentPatchFilter")
        self.playersPerRegion = QtWidgets.QLineEdit(self.centralwidget)
        self.playersPerRegion.setGeometry(QtCore.QRect(460, 20, 111, 31))
        self.playersPerRegion.setObjectName("playersPerRegion")
        self.gamesPerPlayer = QtWidgets.QLineEdit(self.centralwidget)
        self.gamesPerPlayer.setGeometry(QtCore.QRect(590, 20, 111, 31))
        self.gamesPerPlayer.setObjectName("gamesPerPlayer")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(590, 0, 101, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 0, 111, 20))
        self.label_7.setObjectName("label_7")
        self.challengerCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.challengerCheckBox.setGeometry(QtCore.QRect(350, 0, 81, 23))
        self.challengerCheckBox.setChecked(True)
        self.challengerCheckBox.setObjectName("challengerCheckBox")
        self.grandmasterCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.grandmasterCheckBox.setGeometry(QtCore.QRect(350, 20, 101, 23))
        self.grandmasterCheckBox.setObjectName("grandmasterCheckBox")
        self.masterCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.masterCheckBox.setGeometry(QtCore.QRect(350, 40, 82, 23))
        self.masterCheckBox.setObjectName("masterCheckBox")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1475, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "TFT Challenger Meta Evaluator"))
        self.Patch_label.setText(_translate("mainWindow", "Current Patch:"))
        self.euwCheckBox.setText(_translate("mainWindow", "EUW"))
        self.krCheckBox.setText(_translate("mainWindow", "KR"))
        self.traitsButton.setText(_translate("mainWindow", "Traits"))
        self.championsButton.setText(_translate("mainWindow", "Champions"))
        self.itemsButton.setText(_translate("mainWindow", "Items"))
        self.tableWidget.setSortingEnabled(False)
        self.loadDataButton.setText(_translate("mainWindow", "Load Data"))
        self.label.setText(_translate("mainWindow", "Search"))
        self.label_2.setText(_translate("mainWindow", "Trait Filter"))
        self.label_3.setText(_translate("mainWindow", "Champion Filter"))
        self.label_4.setText(_translate("mainWindow", "Tier"))
        self.label_5.setText(_translate("mainWindow", "Star"))
        self.currentPatchFilter.setText(_translate("mainWindow", "11.7"))
        self.playersPerRegion.setText(_translate("mainWindow", "1"))
        self.gamesPerPlayer.setText(_translate("mainWindow", "1"))
        self.label_6.setText(_translate("mainWindow", "Games per Player"))
        self.label_7.setText(_translate("mainWindow", "Players per Region"))
        self.challengerCheckBox.setText(_translate("mainWindow", "Challenger"))
        self.grandmasterCheckBox.setText(_translate("mainWindow", "Grandmaster"))
        self.masterCheckBox.setText(_translate("mainWindow", "Master"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
